
User.destroy_all
Hotel.destroy_all
Review.destroy_all


hotel_1 = Hotel.create(location: "London", price: 600, name: "hotel_1", total_room_number: 10)
hotel_2 = Hotel.create(location: "Manchester", price: 600, name: "hotel_2", total_room_number: 100)
hotel_3 = Hotel.create(location: "Birmingham", price: 600, name: "hotel_3", total_room_number: 20)
hotel_4 = Hotel.create(location: "Edinburgh", price: 600, name: "hotel_4", total_room_number: 15)
hotel_5 = Hotel.create(location:  "Cardiff", price: 600, name: "hotel_5", total_room_number: 103)
hotel_6 = Hotel.create(location: "Belfast", price: 300, name: "hotel_6", total_room_number: 200)
hotel_7 = Hotel.create(location: "London", price: 300, name: "hotel_7", total_room_number: 4)
hotel_8 = Hotel.create(location: "Manchester", price: 300, name: "hotel_8", total_room_number: 102)
hotel_9 = Hotel.create(location: "Birmingham", price: 300, name: "hotel_9", total_room_number: 30)
hotel_10 = Hotel.create(location: "Edinburgh", price: 300, name: "hotel_10", total_room_number: 50)
hotel_11 = Hotel.create(location: "Cardiff", price: 100, name: "hotel_11", total_room_number: 40)
hotel_12 = Hotel.create(location: "Belfast", price: 100, name: "hotel_12", total_room_number: 34)
hotel_13 = Hotel.create(location: "London", price: 100, name: "hotel_13", total_room_number: 40)
hotel_14 = Hotel.create(location: "Manchester", price: 100, name: "hotel_14", total_room_number: 50)
hotel_15 = Hotel.create(location: "Birmingham", price: 100, name: "hotel_15", total_room_number: 80)

user_1 = User.create(first_name: "John", last_name: "Smith", age: 30)
user_2 = User.create(first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, age: Faker::Number.within(16..75))
user_3 = User.create(first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, age: Faker::Number.within(16..75))
user_4 = User.create(first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, age: Faker::Number.within(16..75))
user_5 = User.create(first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, age: Faker::Number.within(16..75))
user_6 = User.create(first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, age: Faker::Number.within(16..75))
user_7 = User.create(first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, age: Faker::Number.within(16..75))
user_8 = User.create(first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, age: Faker::Number.within(16..75))
user_9 = User.create(first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, age: Faker::Number.within(16..75))
user_10 = User.create(first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, age: Faker::Number.within(16..75))

review_1 = Review.create(content: "Excellent hotel", star_rating: "*****", user_id: user_1.id, hotel_id: hotel_1.id)
review_2 = Review.create(content: "Rubbish, not worth the money!!", star_rating: "*", user_id: user_2.id, hotel_id: hotel_2.id)
review_3 = Review.create(content: "Superb!", star_rating: "*****", user_id: user_1.id, hotel_id: hotel_3.id)
review_4 = Review.create(content: "Great hotel!", star_rating: "****", user_id: user_3.id, hotel_id: hotel_4.id)
review_5 = Review.create(content: "Superb hotel, highly recommended!", star_rating: "*****", user_id: user_1.id, hotel_id: hotel_5.id)
review_6 = Review.create(content: "Average rooms but good location", star_rating: "***", user_id: user_4.id, hotel_id: hotel_6.id)
review_7 = Review.create(content: "Was OK!", star_rating: "***", user_id: user_1.id, hotel_id: hotel_7.id)
review_8 = Review.create(content: "Noisy location but clean rooms, was ok stay!", star_rating: "***", user_id: user_5.id, hotel_id: hotel_8.id)
review_9 = Review.create(content: "Good for price! Nice location!", star_rating: "****", user_id: user_1.id, hotel_id: hotel_9.id)
review_10 = Review.create(content: "Rubbish hotel", star_rating: "*", user_id: user_6.id, hotel_id: hotel_10.id)
review_11 = Review.create(content: "Great budget hotel, would recommend", star_rating: "****", user_id: user_1.id, hotel_id: hotel_11.id)
review_12 = Review.create(content: "Rubbish hotel", star_rating: "*", user_id: user_7.id, hotel_id: hotel_12.id)
review_13 = Review.create(content: "Don't stay here", star_rating: "*", user_id: user_1.id, hotel_id: hotel_13.id)
review_14 = Review.create(content: "Good hotel, excellent value for money", star_rating: "***", user_id: user_8.id, hotel_id: hotel_15.id)
review_15 = Review.create(content: "Excellent hotel", star_rating: "*****", user_id: user_1.id, hotel_id: hotel_14.id)
review_16 = Review.create(content: "10/10", star_rating: "*****", user_id: user_9.id, hotel_id: hotel_1.id)
review_17 = Review.create(content: "Poor quality for the price", star_rating: "**", user_id: user_10.id, hotel_id: hotel_2.id)
review_18 = Review.create(content: "Very good hotel!", star_rating: "****", user_id: user_10.id, hotel_id: hotel_3.id)
review_19 = Review.create(content: "Was ok stay but very over-priced!", star_rating: "***", user_id: user_2.id, hotel_id: hotel_4.id)
review_20 = Review.create(content: "Excellent quality!", star_rating: "*****", user_id: user_9.id, hotel_id: hotel_5.id)
review_21 = Review.create(content: "Very good, would recommend", star_rating: "****", user_id: user_3.id, hotel_id: hotel_6.id)
review_22 = Review.create(content: "Good hotel & location for price paid", star_rating: "****", user_id: user_4.id, hotel_id: hotel_7.id)
review_23 = Review.create(content: "Nice hotel, enjoyed our stay", star_rating: "****", user_id: user_5.id, hotel_id: hotel_8.id)
review_24 = Review.create(content: "Very good, recommended", star_rating: "*****", user_id: user_6.id, hotel_id: hotel_9.id)
review_25 = Review.create(content: "Not great hotel but very good price", star_rating: "***", user_id: user_7.id, hotel_id: hotel_10.id)
review_26 = Review.create(content: "Rubbish hotel", star_rating: "*", user_id: user_8.id, hotel_id: hotel_11.id)
review_27 = Review.create(content: "Terrible!", star_rating: "*", user_id: user_9.id, hotel_id: hotel_12.id)
review_28 = Review.create(content: "NOT recommended!", star_rating: "*", user_id: user_10.id, hotel_id: hotel_13.id)
review_29 = Review.create(content: "Excellent hotel", star_rating: "*****", user_id: user_1.id, hotel_id: hotel_14.id)
review_30 = Review.create(content: "Basic hotel good location, ok for price paid", star_rating: "***", user_id: user_2.id, hotel_id: hotel_15.id)
